apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: userservice
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: userservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: activityservice
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: activityservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aiservice
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: aiservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
